[
  {
    "id": "1",
    "createdAt": "2020-11-07T23:51:16.908Z",
    "recipeName": "Cireng Salju",
    "desc": "Cireng Salju renyah, lembut dan gurih di mulut..",
    "ingredients": [
      "200gr tepung tapioka",
      "4 siung bawang putih",
      "2 batang daun bawang",
      "garam dan merica secukupnya",
      "1 sdt penyedap ayam",
      "180ml air panas"
    ],
    "steps": [
      " Geprek bawang putih dan potong daun bawang. Campurkan ke dalam tepung tapioka dan garam",
      " Rebus air 180 ml, dan tambahkan 2 sdm tepung tapioka, aduk sampai seperti lem (disebutnya adonan biang)",
      " Terus biang itu dicampurin ke sisa tapioka, dicampur dan diuleni",
      " Uleni adonan pake sendok atau tangan sampe adonan bisa dibentuk",
      " Ambil adonan 10 gr, bulatkan kalo mau diberi isian beri sedikit Keju Mozza. atau beri isian lainnya sesuai selera",
      " Lalu Pipihkan adonan cireng seperti ini, jangan terlalu tipis ya.. apalagi kalo pake isian",
      " Hasil nya Lumayan banyak nih.. jadi 13-15 biji tergantung ukuran dan berat adonan",
      " Goreng cireng dalam minyak panas dan api sedang. kalo adonan sesuai step diatas, cireng bakal mengembang dan berwarna putih",
      " Cantik kan hasil nya.. aku sarankan segera dimakan deh pas anget anget gini, enak banget masih renyah renyah lembut gitu"
    ],
    "imgUrl": "https://assets.pikiran-rakyat.com/crop/0x112:960x697/x/photo/2020/07/25/395810615.jpg",
    "category": "Indonesia"
  },
  {
    "id": "2",
    "createdAt": "2020-11-07T22:56:12.575Z",
    "recipeName": "Pisang Molen",
    "desc": "Kulitnya krenyes dalemnya nyesss ",
    "ingredients": [
      "1 buah pisang tanduk potong",
      "15 sdm tepung terigu",
      "3 sdm gula pasir",
      "3 sdm margarine",
      "1/2 gelas belimbing air"
    ],
    "steps": [
      " Campur semua bahan kulit jd 1 kecuali air",
      " aduk rata lalu tuangi air sedikit2 sambil di uleni hingga adonan tdk menempel di tangan",
      " Ambil sedikit adonan lalu gilas dgn rollpin atau dgn botol hingga ketebalan yg di inginkan",
      " Taruh pisang di atas adonan yg sdh di gilas td lalu gulung",
      " rapatkan ujungnya",
      " Goreng dlm minyak panas hingga kuning keemasan,angkat dan sajikan"
    ],
    "imgUrl": "https://i0.wp.com/resepkoki.id/wp-content/uploads/2017/03/Resep-Molen-pisang.jpg?fit=2322%2C2322&ssl=1",
    "category": "Indonesia"
  },
  {
    "id": "3",
    "createdAt": "2020-11-08T06:06:15.782Z",
    "recipeName": "Opor Ayam",
    "desc": "Lebaran sebentar lagi? jangan khawatir opor ayam ini sangat mudah di masak!",
    "ingredients": [
      "2 ekor ayam dipotong jadi 8",
      "2 kotak santan instan",
      "6 batang serai(geprek)",
      "sejempol laos(geprek)",
      "10 lembar daun salam",
      "Air untuk rebus ayam",
      "20 siung bawang merah",
      "10 siung bawang putih",
      "5 butir kemiri",
      "sejempol jahe",
      "1 sdm ketumbar bubuk",
      "1 sdt merica bubuk",
      "1 sdt kuyit bubuk",
      "1 sdt garam",
      "1 sdt gula",
      "2sdm minyak goreng"
    ],
    "steps": [
      " Cuci bersih ayam",
      " Sisihkan ati ampelanya.",
      " Rebus selama 20 menit lalu tiriskan agar mengurangi minyak dan amis.",
      " Blender bumbu halus",
      " lalu tumis dengan serai dan daun salam di dalam panci sambil tambahkan sedikit air. Aduk hingga wangi.",
      " Masukkan ayam dan air (bukan air dari rebusan ayam tadi) hingga ayam terendam.",
      " Aduk hingga mendidih lalu tambahkan santan instan.",
      " Tes rasa dengan garam dan gula.",
      " Bila sudah pas, sajikan dengan nasi dan sambal."
    ],
    "imgUrl": "https://asset.kompas.com/crops/VhBtjyhh4_yofTk-0OzaGD7s-7A=/0x0:1000x667/750x500/data/photo/2020/05/21/5ec67d4e9e153.jpg",
    "category": "Indonesia"
  },
  {
    "id": "4",
    "createdAt": "2020-11-07T19:56:40.988Z",
    "recipeName": "Rendang",
    "desc": "Rendang Khas Minang Rancak Banaa",
    "ingredients": [
      "1. kg daging sapi (bagusnya daging bagian kepala)",
      "1 lembar daun kunyit",
      "3 lembar daun jeruk",
      "2 lembar daun salam",
      "Santan dari 4 butir kelapa",
      "3 sendok makan garam",
      "100 gr bawang merah",
      "100 gr bawang putih",
      "150 gr cabai merah keriting",
      "1 ruas jari jahe",
      "2 ruas jari laos",
      "3 batang serai"
    ],
    "steps": [
      " Potong-potong daging berbentuk kotak dan haluskan bumbu halus dengan blender atau batu giling.",
      " Siapkan wajan, masukkan semua bahan dan bumbu halus. Kemudian masak semua bahan dengan api besar sampai mendidih, sambil diaduk-aduk.",
      " Setelah mendidih kecilkan api menjadi sedang. Aduk-aduk dan masak sampai santan mengeluarkan minyak.",
      " Setelah santan mengeluarkan minyak, kecilkan api kembali. Lalu aduk-aduk sesekali agar rendang tidak gosong dan masak sampai rendang mengering.",
      " Jika menginginkan rendang yang kering, waktu memasak yang diperlukan kira-kira selama delapan jam."
    ],
    "imgUrl": "https://asset.kompas.com/crops/YKSBLbCigyp8uVtrfdqq57cS4Is=/0x3:977x654/750x500/data/photo/2020/06/30/5efaf91e0ec2c.jpg",
    "category": "Indonesia"
  },
  {
    "id": "5",
    "createdAt": "2020-11-07T16:30:36.660Z",
    "recipeName": "Soto Ayam Lamongan",
    "desc": "Soto Ayam Khas Lamongan, rasanya mantap buatnya ngga ribett!!",
    "ingredients": [
      "1 ekor (700 g) ayam kampung",
      "2.5 L air",
      "5 lembar daun jeruk",
      "1 sdt garam",
      "1 sdt gula pasir",
      "2 sdm Bango Kecap Manis Light",
      "2 batang serai, memarkan",
      "2 cm lengkuas, memarkan",
      "2 sdm minyak, untuk menumis",
      "300 ml minyak, untuk menggoreng",
      "12 butir bawang merah",
      "8 siung bawang putih",
      "2 cm jahe",
      "3 cm kunyit bakar",
      "4 butir kemiri",
      "1 sdm bawang putih goreng",
      "1 sdm bawang merah goreng",
      "50 g suun kering, seduh air hangat, tiriskan",
      "2 buah tomat, potong kasar",
      "2 batang daun seledri, cincang halus",
      "3 butir telur ayam rebus",
      "200 g kol, iris halus"
    ],
    "steps": [
      " Dalam panci, rebus air dan ayam dengan api kecil. Masak hingga ayam matang dan lunak. Saring kaldu dan sisihkan.",
      " Panaskan minyak, goreng ayam hingga kecokelatan. Suwir-suwir.",
      " Dalam panci, rebus kembali kaldu hingga mendidih.",
      " Panaskan minyak, tumis bumbu halus, serai, lengkuas, dan daun jeruk hingga harum.",
      " Tuang tumisan bumbu, garam, gula, dan Bango Kecap Manis Light ke dalam rebusan kaldu. Masak hingga mendidih.",
      " Tata bahan pelengkap di mangkuk, kecuali sambal. Beri suwiran ayam, siram dengan kuah soto. Sajikan selagi hangat."
    ],
    "imgUrl": "https://sifu.unileversolutions.com/image/id-ID/recipe-topvisual/2/1260-709/soto-ayam-lamongan-50447750.jpg",
    "category": "Indonesia"
  },
  {
    "id": "6",
    "createdAt": "2020-11-08T01:07:43.117Z",
    "recipeName": "Martabak Telor Daging Bayam",
    "desc": "Camilan Gurih Bikin Nagihhhh",
    "ingredients": [
      "12 lembar kulit lumpia",
      "Minyak untuk menumis dan menggoreng",
      "200 g daging sapi cincang",
      "2 siung bawang putih",
      "3 lembar daun jeruk",
      "1 batang serai, memarkan",
      "1/2 sdt merica putih bubuk",
      "2 batang daun bawang,, iris tipis",
      "80 g bawang bombay, cincang halus",
      "70 g daun bawang hijau",
      "2 sdt kari bubuk",
      "1/2 sdt Royko Kaldu Sapi",
      "2 butir telur ayam"
    ],
    "steps": [
      " Isi: Panaskan 2 sdm minyak, tumis bawang bombay dan bawang putih hingga harum. Masukkan daging, aduk hingga berubah warna. Masukkan daun jeruk, kari bubuk, serai, Royco Kaldu Sapi, dan merica, aduk rata.",
      " Masak hingga daging matang. Masukkan bayam, aduk hingga bayam layu. Angkat. Sisihkan. Setelah tidak panas, aduk rata bersama daun bawang dan telur ayam.",
      " Martabak: Siapkan kulit lumpia, ambil 1 sdm adonan isi ke bagian tengahnya. Lipat membentuk amplop dengan rapi, rekatkan dengan air. Ulangi proses serupa pada sisa bahan hingga habis.",
      " Panaskan minyak, goreng martabak sambil siram minyak ke permukaannya hingga martabak kecokelatan dan garing. Angkat. Sajikan."
    ],
    "imgUrl": "https://www.masakapahariini.com/wp-content/uploads/2020/10/Martabak-Telor-Bayam-780x440.jpg",
    "category": "Indonesia"
  },
  {
    "id": "7",
    "createdAt": "2020-11-07T23:22:56.641Z",
    "recipeName": "Capcay Kuah Telur",
    "desc": "Jadikan Makan Malammu Semakin Lengkap",
    "ingredients": [
      "200 g udang, kupas",
      "100 g kembang kol",
      "30 g kacang kapri",
      "1 buah tomat",
      "3 butir bawang merah",
      "1/2 sdt royko kaldu ayam",
      "1 butir telur ayam",
      "50 g brokoli",
      "1 buah wortel",
      "1 sdt merica putih bubuk",
      "2 siung bawang putih",
      "1 sdm bango kecap manis",
      "bawang bombay",
      "minyak goreng"
    ],
    "steps": [
      " Haluskan bawang merah, bawang putih, bersama garam. Sisihkan.",
      " Tumis bawang bombay yang diiris tipis. Masukkan bumbu yang sudah dihaluskan, beri sedikit air.",
      " Masukkan udang kupas, wortel, kembang kol, dan brokoli. Tumis sampai layu.",
      " Tambahkan merica bubuk, Bango Kecap Manis, dan saus tiram.",
      " Masukkan kacang kapri, lalu aduk sampai rata tambahkan Royco Kaldu Ayam.",
      " Masukkan 1 butir telur dan aduk-aduk hingga menyerupai serabut. Angkat dan sajikan."
    ],
    "imgUrl": "https://www.masakapahariini.com/wp-content/uploads/2019/10/shutterstock_343043879-780x440.jpg",
    "category": "Indonesia"
  },
  {
    "id": "8",
    "createdAt": "2020-11-08T01:44:08.914Z",
    "recipeName": "Dimsum Ayam",
    "desc": "Dimsum Ayam Seenak Restoran!",
    "ingredients": [
      "400g daging ayam giling",
      "150g udang kupas, cincang halus",
      "3 siung bawang putih, haluskan",
      "1 sdm bawang goreng, haluskan",
      "1 batang daun bawang, iris tipis",
      "1 sdm tepung terigu",
      "3 sdm tepung sagu",
      "2 butir telur",
      "1 sdt Royco Kaldu Ayam",
      "½ sdt merica putih bubuk",
      "½ sdt gula pasir",
      "½ sdt garam",
      "3 sdm minyak wijen"
    ],
    "steps": [
      " Aduk rata semua bahan adonan dimsum. Sisihkan. Panaskan dandang atau panci pengukus. Sisihkan",
      " Ambil selembar kulit pangsit, taruh 1sdt adonan siomay di tengahnya. Lipat keliling sisi kulitnya, lalu beri parutan wortel ke atasnya. Ulangi proses serupa pada sisi bahannya",
      " Kukus dimsum kedalam dandang panas selama sekitar 30 menit",
      " Sajikan dimsum ayam dengan saus sambal"
    ],
    "imgUrl": "https://cdn.yummy.co.id/content-images/images/20200418/Y2pgGjMeQuXmoqojohbSgJiEsWQIlyKE-31353837313934383234d41d8cd98f00b204e9800998ecf8427e_800x800.jpg",
    "category": "Indonesia"
  },
  {
    "id": "9",
    "createdAt": "2020-11-08T02:27:30.188Z",
    "recipeName": "Nasi Goreng Ayam Suwir",
    "desc": "Istimewa dan Mudah Dimasak di Rumah",
    "ingredients": [
      "400g nasi putih",
      "2 buah sosis sapi, kerat ujungnya, iris kecil-kecil",
      "100g ayam goreng, suwir",
      "1 butir telur ayam",
      "3 butir bawang merah, iris tipis",
      "2 siung bawang putih, cincang halus",
      "2 buah cabai merah, buang biji, iris tipis",
      "2 sdm Bango Kecap Manis",
      "1 batang daun bawang",
      "1 sdm kecap asin",
      "½ sdt merica putih bubuk",
      "1 sdt garam",
      "2 sdm minyak, untuk menumis"
    ],
    "steps": [
      " Panaskan minyak, tumis bawang merah, bawang putih, dan cabai hingga harum",
      " Masukkan nasi, telur, dan ayam suwir. Aduk rata",
      " Tambahkan kecap asin, bango kecap manis, merica dan garam. Aduk rata",
      " Tambahkan sosis dan daun bawang. Aduk rata",
      " Angkat dan sajikan"
    ],
    "imgUrl": "https://www.masakapahariini.com/wp-content/uploads/2019/11/shutterstock_1067156342-780x440.jpg",
    "category": "Indonesia"
  },
  {
    "id": "10",
    "createdAt": "2020-11-07T19:58:35.668Z",
    "recipeName": "Ayam Bakar",
    "desc": "Bikin Suami Betah Dirumah",
    "ingredients": [
      "8 potong daging ayam",
      "1 buah jeruk nipis",
      "2 batang serai, memarkan",
      "8 lembar daun jeruk",
      "2 sdm Bango Kecap Manis",
      "½ sdm air asam jawa",
      "1 sdt garam",
      "½ sdt gula pasir",
      "½ sdt merica putih bubuk",
      "250 ml air",
      "2 sdm minyak sayur",
      "4 siung bawang putih, haluskan",
      "10 butir bawang merah, haluskan",
      "2 buah cabai merah keriting",
      "2 cm jahe",
      "2 cm lengkuas",
      "1 sdt garam"
    ],
    "steps": [
      " Cuci bersih ayam dan lumuri dengan air jeruk nipis dan garam, lalu diamkan 15 menit",
      " Panaskan minyak. Tumis bumbu ungkep ayam bakar, tambahkan daun jeruk dan serai hingga harum. Masukkan ayam, aduk sampai berubah warna",
      " Tambahkan kecap manis bango, lada putih bubuk, gula pasir, tuangkan air dan asam jawa. Aduk merata, hingga matang dan bumbu meresap",
      " Bakar ayam sambil sesekali dibalik dan diolesi bumbu hingga harum. Angkat dan hidangkan"
    ],
    "imgUrl": "https://asset.kompas.com/crops/1d1gR1Q2dYRdPd_3mO2QyB0KjIk=/0x0:1000x667/750x500/data/photo/2020/04/26/5ea556518c494.jpg",
    "category": "Indonesia"
  },
  {
    "id": "11",
    "createdAt": "2020-11-08T09:10:08.474Z",
    "recipeName": "Zuppa Soup Ayam Jamur",
    "desc": "Makanan Khas Italia Mudah Dibuat Oleh Bunda!",
    "ingredients": [
      "1. 2 sdm margarin",
      "2. 1 buah bawang bombay ukuran besar, cincang kasar",
      "3. 50 gram tepung terigu",
      "4. 250 ml susu cair",
      "5. 750 ml liter kaldu ayam",
      "6. 200 gram dada ayam rebus, potong dadu",
      "7. 100 gram jamur kaleng, iris tipis jadi 3 bagian",
      "8. ½ sdt merica bubuk",
      "9. 2 sdt garam",
      "10. 1 kuning telur kocok untuk olesan",
      "11. Keju parut untuk taburan"
    ],
    "steps": [
      " Panaskan oven dengan suhu 180’ C.",
      " Panaskan margarin dan tumis bawang bombay sampai harum dan agak layu.",
      " Masukkan tepung terigu. Aduk dan masak sampai tepung matang (tidak menempel pada wajan).",
      " Masukkan susu cair dan kaldu ayam secara bertahap. Aduk rata sampai tepung terigu tidak bergerindil. Masak sampai mendidih.",
      " Masukkan ayam, jamur, merica dan garam. Aduk rata dan angkat.",
      " Tuang sup ke dalam mangkok tahan panas/ramekin/mangkuk alumunium foil. Tutup bagian atasnya dengan lembaran kulit pastry. Olesi kuning telur dan taburi keju parut.",
      " Panggang sup 15 menit sampai kulit pastry berwarna kuning kecokelatan dan kering.",
      " Angkat dan sajikan selagi panas."
    ],
    "imgUrl": "https://www.masakapaya.com/Uploads/zuppa-soup.jpg?width=1280&quality=95",
    "category": "International"
  },
  {
    "id": "12",
    "createdAt": "2020-11-07T17:02:33.053Z",
    "recipeName": "Kimchi",
    "desc": "Makanan Khas Korea Kesukaan Anak Gadis!",
    "ingredients": [
      "1. 3 sdm garam",
      "2. 1 wortel potong tipis memanjang",
      "3. 6 cangkir air",
      "4. 900 gr sawi putih, potong kotak sedang.",
      "5. 6 tangkai daun bawang, potong dan sayat tipis",
      "6. 1/2 sdm jahe segar, cincang",
      "7. 3 sdm saus ikan/udang Korea. Namun jangan menggunakan bahan ini jika Anda ingin membuat kimchi vegetarian.",
      "8. 1/4 cangkir cabai kering Korea halus (atau cabai halus lainnya)",
      "9. 1 cangkir lobak Korea, cincang kasar",
      "10. 1 sdm gula"
    ],
    "steps": [
      " Sebelum membuatnya, cucilah semua bahan mulai dari sawi, wortel, dan sayuran lainnya agar terhindar dari kuman.",
      " Larutkan garam ke dalam air pada wadah yang bersih.",
      " Masukkan sawi putih ke dalam air garam tersebut, tekan, dan tutup sawi hingga 12 jam. Lalu diamkan.",
      " Setelah 12 jam, keringkan sawi dan sisihkan airnya. Setelah itu campurkan bahan lainnya seperti wortel dan lobak. Tambahkan sedikit garam.",
      " Langkah selanjutnya, haluskan, dan campurkan bumbu kimchinya seperti jahe, saus ikan, bubuk cabai.",
      " Setelah bumbu jadi, campurkan bumbu pada kimchi secara merata.",
      " Masukkan kembali bahan kimchi ke wadah besar tertutup, masukkan sedikit air garam yang sudah disisihkan sebelumnya.",
      " Setelah semua masuk ke dalam wadah, tutup rapat, dan diamkan selama sehari atau lebih. Hal ini sesuai selera untuk tingkat keasamannya.",
      " Saat tingkat keasaman sudah sesuai, kimchi sudah bisa dinikmati."
    ],
    "imgUrl": "https://www.koreanbapsang.com/wp-content/uploads/2016/10/DSC_1843-e1477360668451.jpg",
    "category": "International"
  },
  {
    "id": "13",
    "createdAt": "2020-11-08T02:57:22.216Z",
    "recipeName": "Sushi",
    "desc": "Makanan Khas Jepang Yang Telah Menjajah Kita",
    "ingredients": [
      "1. 150 gr fillet ayam",
      "2. 1 sdm royco ayam goreng",
      "3. Minyak untuk menggoreng",
      "4. 400 gr beras",
      "5. 100 gr beras ketan",
      "6. 1 bungkus royco kaldu ayam",
      "7. 600 ml air",
      "8. 1 buah mentimun iris panjang",
      "9. 2 buah telur dadar iris panjang",
      "10. 3 sdm mayo",
      "11. 1 sdm sambal botol",
      "12. 4 lembar nori"
    ],
    "steps": [
      " Lumuri dada ayam dengan royco bumbu komplit ayam goreng",
      " Dalam mangkuk terpisah aduk mayo dan sambal menjadi satu",
      " Rendam beras ketan selama 15 menit",
      " Tiriskan beras ketan dan cuci bersih bersama beras",
      " Masukan ke dalam rice cooker bersama air dan royco, masak sampai matang",
      " Menggunakan 'Sushi Mat' letakan nori, nasi dipermukaan nori.",
      " Pada satu sisi letakan ayam goreng, spicy mayo, timun, dan telur dadar, kemudian gulung sambil padatkan. iris iris dan sajikan"
    ],
    "imgUrl": "https://cdn-2.tstatic.net/wow/foto/bank/images/sushi_20180220_120810.jpg",
    "category": "International"
  },
  {
    "id": "14",
    "createdAt": "2020-11-08T03:40:31.878Z",
    "recipeName": "Pizza",
    "desc": "Numero Unooo Bundddd",
    "ingredients": [
      "1. 500 gr tepung terigu tinggi",
      "2. 1 sdm gula",
      "3. 7 gr ragi instan",
      "4. 1 1/2sdt garam",
      "5. 50 ml olive oil",
      "6. 360 ml air es",
      "7. Sedikit tambahan terigu untuk taburan di meja Cara membuat"
    ],
    "steps": [
      " Dalam mangkuk besar campurkan tepung terigu, gula dan ragi",
      " Masukkan olive oil",
      " Tambahkan air sedikit demi sedikit, aduk rata dan uleni sampai kalis",
      " Tambahkan sedikit tepung jika adonan terlalu lengket",
      " Siapkan wadah yang sudah dilumuri minyak, masukkan adonan tutup dengan plastik wrap masukkan kulkas semalaman",
      " Keluarkan adonan dari kulkas, diamkan suhu ruangan 30 menit kempeskan adonan lalu bagi 3 atau sesuai selera."
    ],
    "imgUrl": "https://www.qsrmagazine.com/sites/default/files/styles/story_page/public/phut_0.jpg?itok=h30EAnkk",
    "category": "International"
  },
  {
    "id": "15",
    "createdAt": "2020-11-07T19:53:48.895Z",
    "recipeName": "BBQ Ribs",
    "desc": "Makanan Khas Amerika Khususnya Negara Bagian Texas",
    "ingredients": [
      "1. 1 kg iga sapi berdaging, potong-potong",
      "2. 1 sdm bawang putih bubuk",
      "3. 1 sdm paprika bubuk",
      "4. 1 sdm merica hitam tumbuk kasar",
      "5. 1 sdm garam laut/kasar",
      "6. 1 sdm margarin",
      "7. 25 g cabai rawit giling kasar",
      "8. 50 g cabai merah giling kasar",
      "9. 50 g bawang putih, cincang halus",
      "10. 50 g bawang merah, cincang halus",
      "11. 150 ml saus tomat",
      "12. 75 ml kecap manis",
      "13. 2 sdm merica hitam tumbuk kasar"
    ],
    "steps": [
      " Lumuri iga sapi dengan bumbu Dry Rub, diamkan selama 2 jam di dalam kulkas.",
      " Masukkan ke dalam loyang atau wadah tahan panas. Tuangi air secukupnya. Tutup dengan kertas aluminium.",
      " Panggang dalam oven panas 200oC selama 2 jam hingga daging empuk. Angkat.",
      " Tumis cabai dan bawang hingga layu.",
      " Masukkan bahan lainnya,aduk hingga mendidih. Angkat.",
      " Panaskan panggangan di atas bara api.",
      " Olesi iga dengan saus BBQ, panggang hingga saus menempel.",
      " Angkat, sajikan dengan sisa saus BBQ."
    ],
    "imgUrl": "https://www.homesicktexan.com/wp-content/uploads/2019/05/Apricot-chipotle-ribs_DSC5291-2.jpg",
    "category": "International"
  },
  {
    "id": "16",
    "createdAt": "2020-11-07T10:51:29.476Z",
    "recipeName": "Doner Kebab",
    "desc": "Makanan Khas Turki Buatnya Gampang Banget Gapake Ribet!!",
    "ingredients": [
      "1. 500 gram daging kambing, cincang",
      "2. 3 siung bawang putih, cincang",
      "3. 1 sendok makan tepung terigu",
      "4. 2 sendok makan minyak zaitun",
      "5. 1 sendok makan daun selederi cincang",
      "6. 1 sendok teh jintan bubuk",
      "7. 1 sendok teh kayu manis bubuk",
      "8. 3 sendok makan ketumbar bubuk",
      "9. 1 butir telur, kocok",
      "10. 1 sendok teh garam halus",
      "11. ½ sendok teh merica bubuk",
      "12. 2 buah jeruk lemon",
      "13. 4 buah roti pita",
      "14. 4 lembar daun selada, cabik-cabik",
      "15. 4 semdok makan yoghurt tawar",
      "16. 4 tangkai daun mint"
    ],
    "steps": [
      " Panaskan panggangan dengan api sedang.",
      " Alasi loyang 28x8 sentimeter dengan kertas roti dan olesi margarin.",
      " Campur dan aduk rata daging kambing cincang, bawang putih, tepung terigu, minyak zaitun, seledri, jintan, kayu manis, ketumbar, telur, garam, daun seledri, dan merica dalam mangkuk.",
      " Letakkan di atas loyang dan ratakan.",
      " Panggang daging selama 4 menit hingga berwarna kecoklatan.",
      " Buang cairan yang ada pada loyang, lalu letakkan kembali daging ke atas talenan.",
      " Buang kertas roti, lalu letakkan kembali daging di atas loyang. Panggang kembali hingga matang.",
      " Potong daging ukuran dadu kecil, lalu beri air jeruk lemon.",
      " Tata ke atas roti pita bersama daun selada, yoghurt, dan daun mint. Hidangkan selagi hangat."
    ],
    "imgUrl": "https://www.globalfranchisemagazine.com/images/made/assets/images/companies/GDK_product_shots_698_432_82_int_c1.jpg",
    "category": "International"
  },
  {
    "id": "17",
    "createdAt": "2020-11-08T06:41:57.778Z",
    "recipeName": "Nasi Ayam Hainan",
    "desc": "Makanan Khas Singapur Yang Rasanya Enak Banget!",
    "ingredients": [
      "1. 350 gr beras, cuci bersih, tiriskan",
      "2. 6 siung bawang putih cincang",
      "3. 3 cm jahe iris2 tipis",
      "4. 1 lembar daun pandan, ikat",
      "5. 1/2 sdt merica",
      "6. 1 sdt kaldu jamur bubuk",
      "7. 1/2 sdt kaldu ayam bubuk",
      "8. 650 ml kaldu ayam hasil rebusan",
      "9. 1 sdt minyak wijen",
      "10. 1 sdm mentega",
      "11. 1 sdm minyak goreng",
      "12. 1 ekor ayam kampung",
      "13. 2,5 lt air",
      "14. 2 batang daun bawang",
      "15. 1/2 buah bawang bombay potong 4",
      "16. 3 cm jahe iris tipis",
      "17. 1/2 sm garam"
    ],
    "steps": [
      " Ayam rebus: masukkan daun bawang, bawang bombay dan jahe ke dalam perut ayam. Rebus ayam dengan air dan garam sampai empuk. Angkat dan pisahkan daging dari tulang, lumuri dengan minyak wijen, potong, sisihkan.",
      " Nasi: Tumis bawang putih dan jahe dengan minyak dan mentega sampai harum, masukkan beras, aduk rata.",
      " Tuang kaldu ayam dan beri bumbu kecuali minyak wijen, aduk dan masak hingga jadi aron. Masukkan minyak wijen, aduk rata, kukus sampai matang. Sajikan dengan potongan ayam rebus dengan ditaburi bawang putih goreng, dan telur kecap."
    ],
    "imgUrl": "https://doyanresep.com/wp-content/uploads/2020/02/resep-nasi-ayam-hainan.jpg",
    "category": "International"
  },
  {
    "id": "18",
    "createdAt": "2020-11-07T21:45:34.008Z",
    "recipeName": "Meat Pie",
    "desc": "Hidangan Khas Australia Yang Rasanya Nyessss",
    "ingredients": [
      "1. 2 sdm minyak zaitun",
      "2. 50 g bawang bombay, kupas, potong dadu 1 cm",
      "3. 2 siung bawang putih, haluskan",
      "4. 2 batang daun thyme, ambil daunnya",
      "5. 50 g wortel, kupas, potong dadu 1 cm",
      "6. 1 batang seledri impor, potong dadu 1 cm",
      "7. 200 g tomat merah, cincang kasar",
      "8. 30 ml cuka masak",
      "9. ½ sdt garam",
      "10. ½ sdt merica hitam bubuk",
      "11. 250 g daging sapi has dalam, potong dadu 2 cm",
      "12. 250 ml air",
      "13. ½ sdm maizena, larutkan dengan 2 sdm air",
      "14. 150 g kulit pie, siap pakai",
      "15. 300 g puff pastry, siap pakai",
      "16. 1 butir telur ayam, kocok lepas, untuk mengoles"
    ],
    "steps": [
      " Panaskan minyak  di dalam wajan di atas api sedang. Masukkan bawang bombay, bawang putih, dan thyme, masak hingga layu.",
      " Tambahkan wortel dan seledri, lanjutkan memasak selama 5 menit. Masukkan tomat, cuka, garam, dan merica hitam, masak sambil diaduk selama 5 menit. Masukkan daging. Tuang air hingga menutupi daging. Didihkan.",
      " Kecilkan api, lanjutkan memasak hingga daging empuk. Tambahkan larutan maizena, aduk rata. Angkat.",
      " Taruh kulit pie di dalam pinggan tahan panas yang sudah diolesi mentega. Beri adonan isi dan tutup dengan puff pastry.",
      " Olesi permukaannya dengan telur hingga rata. Panggang  dalam oven panas bersuhu 200° C hingga matang (± 45 menit). Keluarkan.",
      " Sajikan disertai salad sayuran, mashed potato, gravy, dan saus tomat botolan."
    ],
    "imgUrl": "https://recipetineats.com/wp-content/uploads/2019/04/Meat-Pies_4.jpg",
    "category": "International"
  },
  {
    "id": "19",
    "createdAt": "2020-11-07T22:46:42.375Z",
    "recipeName": "Peking Duck",
    "desc": "Makanan Khas Tiongkok Yang Rasanya Aduhaiiiii",
    "ingredients": [
      "1. 1 Ekor bebek muda",
      "2. 7 sdm madu",
      "3. Jahe 1 ruas jari, kupas dan parut",
      "4. 250 ml air",
      "5. 1 sdt garam",
      "6. 6 sdm kecap manis",
      "7. 6 sdm gula pasir",
      "8. 125 ml air",
      "9. 1 sdt garam dapur",
      "10. 2 1/2 sdm minyak wijen"
    ],
    "steps": [
      " Bersihkan daging bebek hingga organ dalam, cuci hingga bersih, keringkan.",
      " Rebus air hingga mendidih, rebus daging bebek beberapa menit",
      " Satukan pada satu wadah jahe, madiu, air, dan garam, aduk hingga rata.",
      " Lumuri daging bebek pada campuran tadi ingga merata, simpan di lemari pendingin selama 2 jam.",
      " Keluarkan bebek dari lemari pendingin, panggang dalam oven dengan suhu 145 derajat, kurang lebih selama 50 menit. Balik posisi daging bebek panggang kembali selama 40 menit.",
      " Bebek peking siap disantap",
      " Campurkan semua bahan kecuali minyak wijen",
      " Aduk hingga merata, lalu goreng dengan minyak wijen hingga mengental",
      " Saus bebek peking siap menemani sajian bebek peking anda"
    ],
    "imgUrl": "https://thewoksoflife.com/wp-content/uploads/2015/11/peking-duck-recipe-11-1-500x500.jpg",
    "category": "International"
  },
  {
    "id": "20",
    "createdAt": "2020-11-07T11:39:17.018Z",
    "recipeName": "Ayam Tandoori",
    "desc": "Makanan Khas India Yang Rasanya Pedas Dan Gurihhh",
    "ingredients": [
      "1. 800 g paha ayam bawah, buang kulit, kerat-kerat",
      "2. 1 buah jeruk lemon, ambil airnya",
      "3. 1 sdt garam",
      "4. minyak zaitun",
      "5. daun ketumbar, untuk taburan",
      "6. 100 ml yogurt tawar",
      "7. 150 ml yogurt tawar",
      "8. 2 sdt kunyit bubuk",
      "9. 2 sdt paprika bubuk/cabai-bubuk",
      "10. 2 sdt garam masala",
      "11. 1/8 sdt jintan",
      "12. 4 siung bawang putih, haluskan",
      "13. 2 cm jahe, haluskan"
    ],
    "steps": [
      " Lumuri paha ayam dengan air jeruk lemon dan garam, sisihkan.",
      " Campurkan semua bahan bumbu, aduk rata.",
      " Lumuri ayam dengan campuran bumbu hingga rata, simpan dalam kulkas hingga bumbu meresap (1 jam).",
      " Panaskan minyak zaitun dalam wajan datar, panggang ayam selama ±3 menit setiap sisinya, sambil sesekali diolesi bumbu dan dibalik-balik agar matangnya rata. Angkat. Sajikan dengan taburan daun ketumbar."
    ],
    "imgUrl": "https://tandaseru.id/wp-content/uploads/2020/07/ayam-tandoori.jpg",
    "category": "International"
  },
  {
    "id": "21",
    "createdAt": "2020-11-09T08:07:24.242Z",
    "recipeName": "Chicken Cordon Bleu",
    "desc": "Makanan Khas Perancis",
    "ingredients": [
      "1. 1 Buah dada ayam",
      "2. 1 Buah daging asap",
      "3. Slice mozarella, bisa diganti dengan kraft quick melt",
      "4. 1 Butir telur",
      "5. Secukupnya garam",
      "6. Secukupnya lada",
      "7. Secukupnya tepung bumbu serbaguna",
      "8. Secukupnya potato flake, bisa diganti tepung panir"
    ],
    "steps": [
      " Belah dua dada ayam, kemudian iris tipis dada ayam membelah dua tapi jangan sampai putus",
      " Pipihkan dengan pemukul daging, kalau tidak ada bisa pakai ulekan, pelan-pelan memukulnya supaya daging tidak hancur",
      " Taburi garam dan lada secukupnya secara merata",
      " Taruh daging asap di atas dada ayam, lalu keju kemudian gulung. Sematkan tusuk gigi supaya gulungannya tidak terbuka",
      " Balur dengan tepung bumbu serba guna secara merata",
      " Celupkan ke dalam telur yang sudah dikocok secara merata, kemudian balur dengan potato flake atau tepung panir secara merata",
      " Simpan ayam ke dalam kulkas minimal 1 jam",
      " Goreng ayam menggunakan teknik deep fried atau dengan minyak banyak, pastikan minyak sudah panas dan menggunakan api kecil, goreng sampai berwarna cokelat keemasan",
      " Chicken cordon bleu siap disajikan dengan kentang goreng, sayuran dan brown sauce"
    ],
    "imgUrl": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/190523-chicken-cordon-bleu-098-horizontal-1559068476.png?crop=1.00xw:0.752xh;0,0.161xh&resize=1200:*",
    "category": "International"
  }
]